In [4]:
'''1.
Create a function that transposes a 2D matrix.
Examples
transpose_matrix([
[1, 1, 1],
[2, 2, 2],
[3, 3, 3]
]) ➞ [
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]
]
transpose_matrix([
[5, 5],
[6, 7],
[9, 1]
]) ➞ [
[5, 6, 9],
[5, 7, 1]
]'''

import numpy as np
def transpose_matrix(s):
    return np.transpose(s)

print(transpose_matrix([
[1, 1, 1],
[2, 2, 2],
[3, 3, 3]
]))
print('\n ')
print(transpose_matrix(([5, 5],
[6, 7],
[9, 1])))

[[1 2 3]
 [1 2 3]
 [1 2 3]]

 
[[5 6 9]
 [5 7 1]]


In [1]:
'''2.
Given a list of math equations (given as strings), return the percentage of
correct answers as a string. Round to the nearest whole number.
Examples
mark_maths([&quot;2+2=4&quot;, &quot;3+2=5&quot;, &quot;10-3=3&quot;, &quot;5+5=10&quot;]) ➞ &quot;75%&quot;
mark_maths([&quot;1-2=-2&quot;]), &quot;0%&quot;
mark_maths([&quot;2+3=5&quot;, &quot;4+4=9&quot;, &quot;3-1=2&quot;]) ➞ &quot;67%&quot;'''
import math
def mark_maths(s):
    fin_per = ''
    ct = 0
    for i in range(len(s)):
        ss = s[i].split(' ')
        a = ss[0]
        b = ss[2]
        mid_res = ss[4]
        operator = ss[1]
        if operator == '+':
            if int(a)+int(b) == int(mid_res):
                ct += 1
            else:
                continue
        elif operator == '-':
            if int(a)-int(b) == int(mid_res):
                ct += 1
            else:
                continue
        elif operator == '*':
            if int(a)*int(b) == int(mid_res):
                ct+=1
            else:
                continue
        elif operator == '/':
            if int(a)//int(b) == int(mid_res):
                ct += 1
            else:
                continue
    #print(ct)      
    #print(len(s))
    per = math.ceil((ct*100)/len(s))
    return str(per)+'%'

print(mark_maths(['2 + 2 = 4','3 + 2 = 5','10 - 3 = 3 ','5 + 5 = 10']))
print(mark_maths(['2 + 3 = 5','4 + 4 = 9','3 - 1 = 2']))
print(mark_maths(['1 - 2 = -2']))

75%
67%
0%


In [48]:
'''3.
There are two players, Alice and Bob, each with a 3-by-3 grid. A referee
tells Alice to fill out one particular row in the grid (say the second row) by
putting either a 1 or a 0 in each box, such that the sum of the numbers in that
row is odd. The referee tells Bob to fill out one column in the grid (say the first
column) by putting either a 1 or a 0 in each box, such that the sum of the
numbers in that column is even.
Alice and Bob win the game if Alice’s numbers give an odd sum, Bob’s give
an even sum, and (most important) they’ve each written down the same
number in the one square where their row and column intersect.
Examples
magic_square_game([2, &quot;001&quot;], [1, &quot;101&quot;]) ➞ True
magic_square_game([3, &quot;111&quot;], [2, &quot;011&quot;]) ➞ True
magic_square_game([1, &quot;010&quot;], [3, &quot;101&quot;]) ➞ False
# Two lists, Alice [row, &quot;her choice&quot;], Bob [column, &quot;his choice&quot;]'''

def magic_square_game(l1,l2):
    bob_square = [[0,0,0],[0,0,0],[0,0,0]]
    alice_square = [[0,0,0],[0,0,0],[0,0,0]]
    ind2 = l2[0]-1 #Bob's index = 0
    ind1 = l1[0]-1 # Alice index = 1
    # assigning values to bob's square from list values passed
    l2_list = [int(i) for i in l2[1]]
    for i in range(0,len(l2_list)):
        bob_square[i][ind2] = l2_list[i]

    l1_list = [int(i) for i in l1[1]] 
    for i in range(len(l1_list)):
        alice_square[ind1][i] = l1_list[i]
        
    alice_square_sum = 0 # Taking Alice square sum row-wise
    for i in range(len(l1_list)):
        alice_square_sum += alice_square[ind1][i]
        
    bob_square_sum = 0
    for i in range(len(l2_list)):
        bob_square_sum += bob_square[i][ind2]
        
    if (alice_square_sum%2 != 0) and (bob_square_sum%2==0):
        for i in range(len(l1_list)):
            for j in range(len(l2_list)):
                if i ==j and alice_square[ind1][i] == bob_square[j][ind2]:
                    return True
                else:
                    continue
        return False 
    else:
        return False 
              
print(magic_square_game([2,'001'],[1,'101']))
print(magic_square_game([3,'111'],[2,'011']))
print(magic_square_game([1,'010'],[3,'101']))

True
True
False


In [3]:
'''4. 
From point A, an object is moving towards point B at constant velocity va
(in km/hr). From pint B, another object is moving towards point A at constant
velocity vb (in km/hr). Knowing this and the distance between point A and B
(in km), write a function that returns how much time passes until both objects
meet.
Format the output like this:

&quot;2h 23min 34s&quot;
Examples
lets_meet(100, 10, 30) ➞ &quot;2h 30min 0s&quot;
lets_meet(280, 70, 80) ➞ &quot;1h 52min 0s&quot;
lets_meet(90, 75, 65) ➞ &quot;0h 38min 34s&quot;'''
import math
def lets_meet(d,s1,s2):
    res = d/(s1+s2)
    hh = int(str(res).split('.')[0])
    mi = 0
    if hh > 0:
        if type(res) == float:
            mi = int(str(res).split('.')[1])*10
            #print(mi)
            mi = math.ceil((mi/100)*60)
       
        else:
            mi = 0
        return str(hh)+'h  '+str(mi)[0:2]+'min 0s'
    elif hh < 1:
        if type(res) == float:
            mi = float(str(res).split('.')[1])*10
            mi = math.ceil((mi/100)*60)
            print(mi)
            sec = float(str(mi).split('.')[1])
            return '0h '+str(mi)+'min '+str(sec)+'secs'

        
        
print(lets_meet(100,10,30))
print(lets_meet(280,70,80))

2h  30min 0s
1h  52min 0s
